# Generated by Django 5.0.3 on 2024-03-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('transactionTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
