# Generated by Django 5.0.2 on 2024-03-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
