# Generated by Django 5.0.3 on 2024-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transactionTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
