# Generated by Django 5.0.3 on 2024-03-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transactions_transactiontime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
