# Generated by Django 5.0.3 on 2024-03-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_rename_userinfo_transaction_buyerinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='buyerInfo',
            new_name='sellerInfo',
        ),
    ]
