# Generated by Django 5.0.3 on 2024-03-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_rename_buyerinfo_transaction_sellerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionTime',
            field=models.DateTimeField(),
        ),
    ]
