# Generated by Django 5.0.2 on 2024-03-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=25)),
                ('phone', models.PositiveBigIntegerField(blank=True, max_length=11)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
